### ISSUE TITLE
Crash on leaf decay

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#76]
````
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:699) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) ~[po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.AbstractMethodError: net.minecraft.world.WorldServer.getBlockSnapshot(Lcom/flowpowered/math/vector/Vector3i;)Lorg/spongepowered/api/block/BlockSnapshot;
        at org.spongepowered.api.world.Location.getBlockSnapshot(Location.java:607) ~[Location.class:1.8-1446-2.1DEV-0+unknown-b0.git-unknown]
        at net.minecraft.block.BlockLeaves.callLeafDecay(BlockLeaves.java:70) ~[axg.class:?]
        at net.minecraft.block.BlockLeaves.func_180650_b(BlockLeaves.java:198) ~[axg.class:?]
        at net.minecraft.block.Block.func_180645_a(Block.java:428) ~[atr.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:454) ~[qt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221) ~[qt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:693) ~[MinecraftServer.class:?]
        ... 4 more

**Comment by simon816** [comment]
https://github.com/SpongePowered/Sponge/issues/299
Turns out the fix I pushed yesterday was incomplete. Should be fine now https://github.com/SpongePowered/Sponge/commit/da0208023715d8c89aaff9a39b6c743c996b8cff

**Comment by DarkArc** [comment]
@simon816 nope
````
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:699) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) ~[po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.AbstractMethodError: net.minecraftforge.common.util.BlockSnapshot.setBlockState(Lorg/spongepowered/api/block/BlockState;)V
        at net.minecraft.block.BlockLeaves.callLeafDecay(BlockLeaves.java:71) ~[axg.class:?]
        at net.minecraft.block.BlockLeaves.func_180650_b(BlockLeaves.java:198) ~[axg.class:?]
        at net.minecraft.block.Block.func_180645_a(Block.java:428) ~[atr.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:454) ~[qt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221) ~[qt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:693) ~[MinecraftServer.class:?]
        ... 4 more

**Comment by simon816** [comment]
OK, `BlockSnapshot` is not fully implemented. I'll do that now.

**Comment by DarkArc** [comment]
@simon816 Still not fixed...
````
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:699) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) ~[po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
        at org.spongepowered.common.util.VecHelper.toVector(VecHelper.java:52) ~[VecHelper.class:1.8-1446-2.1DEV-0+unknown-b0.git-unknown]
        at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:38) ~[BlockSnapshot.class:?]
        at net.minecraftforge.common.util.BlockSnapshot.getBlockSnapshot(BlockSnapshot.java:96) ~[BlockSnapshot.class:?]
        at net.minecraft.world.World.getBlockSnapshot(World.java:60) ~[aqu.class:?]
        at org.spongepowered.api.world.Location.getBlockSnapshot(Location.java:608) ~[Location.class:1.8-1446-2.1DEV-0+unknown-b0.git-unknown]
        at net.minecraft.block.BlockLeaves.callLeafDecay(BlockLeaves.java:70) ~[axg.class:?]
        at net.minecraft.block.BlockLeaves.func_180650_b(BlockLeaves.java:198) ~[axg.class:?]
        at net.minecraft.block.Block.func_180645_a(Block.java:428) ~[atr.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:454) ~[qt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221) ~[qt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:693) ~[MinecraftServer.class:?]
        ... 4 more

**Comment by simon816** [comment]
Should be good now https://github.com/SpongePowered/Sponge/commit/a9702ad2b2ad0da5cf113cee5cac5447dc10c0d3
